feat: add remix laravel template
heroui-inc/heroui-cli pull request #127
Opened 2024-12-30 07:05 UTC by winchesHe

## 📝 Description

## ✅ Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

2025-03-09 23:38 UTC, jrgarciadev commented
@winchesHe please fix conflicts

2025-03-11 14:56 UTC, winchesHe commented
> @winchesHe please fix conflicts

Fixed

2025-04-19 03:01 UTC, wingkwong requested changes

2025-04-19 03:01 UTC, wingkwong commented on src/actions/init-action.ts
> +      label: 'laravel',
`laravel` -> `Laravel`

2025-04-19 05:43 UTC, winchesHe commented
@wingkwong Updated

2025-04-19 12:11 UTC, wingkwong approved these changes

2025-04-19 12:13 UTC, merged